std = {
    globals = {
        "rawget",
        "next",
        "before_each",
        "pcall",
        "select",
        "tostring",
        "error",
        "type",
        "tonumber",
        "os",
        "io",
        "table",
        "ipairs",
        "pairs",
        "vim",
        "string",
        "require",
        "math",
    },
}
