local is_valid_version_syntax = require("package-info.helpers.is_valid_version_syntax")

describe("Is_valid_version_syntax", function()
    it("should accept plain versions", function()
        assert.is_true(is_valid_version_syntax("1.0.0"))
        assert.is_true(is_valid_version_syntax("^1.0.0"))
        assert.is_true(is_valid_version_syntax("~1.0.0"))
        assert.is_true(is_valid_version_syntax("1.0.0-beta.1"))
        assert.is_true(is_valid_version_syntax("1.0.0+build.5"))
    end)

    it("should accept ranges and tags", function()
        assert.is_true(is_valid_version_syntax("*"))
        assert.is_true(is_valid_version_syntax("latest"))
        assert.is_true(is_valid_version_syntax(">=1.0.0"))
        assert.is_true(is_valid_version_syntax("1.0.0 - 2.0.0"))
        assert.is_true(is_valid_version_syntax("1.0.0 || 2.0.0"))
    end)

    it("should accept protocol based versions", function()
        assert.is_true(is_valid_version_syntax("catalog:"))
        assert.is_true(is_valid_version_syntax("catalog:frontend"))
        assert.is_true(is_valid_version_syntax("workspace:*"))
        assert.is_true(is_valid_version_syntax("npm:react@1.0.0"))
        assert.is_true(is_valid_version_syntax("file:../react"))
        assert.is_true(is_valid_version_syntax("git+ssh://git@github.com/user/repo.git#v1.0.0"))
    end)

    it("should reject templated versions", function()
        assert.is_false(is_valid_version_syntax("^1.0.0<% if (typescript) { %>"))
        assert.is_false(is_valid_version_syntax("1.0.0<% } %>"))
        assert.is_false(is_valid_version_syntax("{{version}}"))
    end)
end)
